name: CI/CD NODOSTUDIO

on: 
  push:
    branches:
      - 'feature/**'

jobs:
  test-feature:
    name: Test on Feature Branch 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses:  actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install 

      - name: Run unit tests
        run: npm run test 



